export const focusSounds = [
  'rain',
  'window',
  'storm',
  'snow',
  'waterfall',
  'stream',
  'seaside',
  'wind',
  'water',
  'leaves',
  'forest',
  'horse',
  'fire',
  'night',
  'coffee',
  'keyboard',
  'birds',
  'train',
  'road',
  'fireworks',
  'underwater',
  'paper',
  'clock',
  'bubbles',
  'white',
  'pink',
  'brown',
] as const

export type FocusSound = (typeof focusSounds)[number]

export const focusSoundNameRecord: Record<FocusSound, string> = {
  rain: 'Rain',
  storm: 'Thunder',
  snow: 'Walk in snow',
  waterfall: 'Waterfall',
  stream: 'Water stream',
  seaside: 'Waves',
  wind: 'Wind',
  water: 'Water',
  leaves: 'Leaves',
  forest: 'Forest',
  fire: 'Campfire',
  night: 'Night',
  coffee: 'Coffee shop',
  keyboard: 'Keyboard',
  window: 'Rain on window',
  birds: 'Birds',
  train: 'Train',
  road: 'Road',
  white: 'White noise',
  pink: 'Pink noise',
  brown: 'Brown noise',
  horse: 'Horse galopp',
  fireworks: 'Fireworks',
  underwater: 'Underwater',
  bubbles: 'Bubbles',
  paper: 'Paper',
  clock: 'Clock',
}
